"""Check sync

Revision ID: 0d2a424967b3
Revises: 920f5442ac7e
Create Date: 2026-08-04 22:54:15.716661
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d2a424967b3'
down_revision: Union[str, None] = '920f5442ac7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_site_articles_published_at'), table_name='site_articles')
    op.drop_index(op.f('idx_site_articles_slug'), table_name='site_articles')
    op.drop_table('site_articles')
    op.alter_column('articles', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('idx_articles_published_at'), table_name='articles')
    op.drop_index(op.f('idx_articles_slug'), table_name='articles')
    op.drop_column('articles', 'reading_time_minutes')
    op.drop_column('articles', 'category_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('category_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('reading_time_minutes', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_articles_slug'), 'articles', ['slug'], unique=False)
    op.create_index(op.f('idx_articles_published_at'), 'articles', [sa.literal_column('published_at DESC')], unique=False)
    op.alter_column('articles', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('site_articles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('excerpt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('featured_image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seo_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('view_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('reading_time_minutes', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('category_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('site_articles_pkey')),
    sa.UniqueConstraint('slug', name=op.f('site_articles_slug_key'))
    )
    op.create_index(op.f('idx_site_articles_slug'), 'site_articles', ['slug'], unique=False)
    op.create_index(op.f('idx_site_articles_published_at'), 'site_articles', [sa.literal_column('published_at DESC')], unique=False)
    # ### end Alembic commands ###