"""Add ai_metadata to articles

Revision ID: 1ec2f3f28162
Revises: 0d2a424967b3
Create Date: 2026-08-05 08:27:13.494572
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec2f3f28162'
down_revision: Union[str, None] = '0d2a424967b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('ai_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'ai_metadata')
    # ### end Alembic commands ###