"""Sync database schema completely

Revision ID: 920f5442ac7e
Revises: 
Create Date: 2026-08-04 22:49:43.656716
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app

# revision identifiers, used by Alembic.
revision: str = '920f5442ac7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('idx_site_articles_published_at'), table_name='site_articles')
    # op.drop_index(op.f('idx_site_articles_slug'), table_name='site_articles')
    # op.drop_table('site_articles')
    op.add_column('articles', sa.Column('user_id', app.core.db_types.Uuid(), nullable=True))
    op.add_column('articles', sa.Column('category_id', app.core.db_types.Uuid(), nullable=True))
    op.add_column('articles', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('articles', sa.Column('ai_generated', sa.Boolean(), nullable=True))
    op.add_column('articles', sa.Column('ai_job_id', app.core.db_types.Uuid(), nullable=True))
    op.alter_column('articles', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('articles', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=True)
    # op.drop_index(op.f('idx_articles_published_at'), table_name='articles')
    # op.drop_index(op.f('idx_articles_slug'), table_name='articles')
    op.create_index(op.f('ix_articles_user_id'), 'articles', ['user_id'], unique=False)
    op.create_foreign_key(None, 'articles', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'articles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'articles', 'ai_jobs', ['ai_job_id'], ['id'], ondelete='SET NULL')
    # op.drop_column('articles', 'category_name')
    # op.drop_column('articles', 'reading_time_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('reading_time_minutes', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('category_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_index(op.f('ix_articles_user_id'), table_name='articles')
    op.create_index(op.f('idx_articles_slug'), 'articles', ['slug'], unique=False)
    op.create_index(op.f('idx_articles_published_at'), 'articles', [sa.literal_column('published_at DESC')], unique=False)
    op.alter_column('articles', 'slug',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('articles', 'title',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('articles', 'ai_job_id')
    op.drop_column('articles', 'ai_generated')
    op.drop_column('articles', 'status')
    op.drop_column('articles', 'category_id')
    op.drop_column('articles', 'user_id')
    op.create_table('site_articles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('excerpt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('featured_image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seo_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('view_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('reading_time_minutes', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('category_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('site_articles_pkey')),
    sa.UniqueConstraint('slug', name=op.f('site_articles_slug_key'))
    )
    op.create_index(op.f('idx_site_articles_slug'), 'site_articles', ['slug'], unique=False)
    op.create_index(op.f('idx_site_articles_published_at'), 'site_articles', [sa.literal_column('published_at DESC')], unique=False)
    # ### end Alembic commands ###